---
title: "Welcome to UBC's Willamette Valley System Injunction assessment interactive graphics webpage"
---

## Introduction
<span style="font-size:120%">This is a simple website that hosts interactive figures to assist UBC's assessment of injunction measures in the Willamette Valley System (WVS). The system is comprised of several high-head dams and associated reservoirs that are operated by the US Army Corps of Engineers in four sub-basins: the North Santiam, South Santiam, McKenzie, and Middle Fork.</span>  

On September 1, 2021, the U.S. District Court for the District of Oregon issued an interim injunction that requires the Corps to undertake specified actions to improve fish passage and water quality at several Willamette Valley Project dams for the benefit of Upper Willamette River (UWR) spring Chinook salmon and UWR winter steelhead salmon, both of which are listed as threatened under the Endangered Species Act. The Corps is working in coordination with the National Marine Fisheries Service, U.S. Fish and Wildlife Service, Bonneville Power Administration, and U.S. Bureau of Reclamation to implement the injunction measures, some of which began in fall 2021.

For full descriptions of the WVS measures, see the [WV Project Injunction webpage](https://www.nwp.usace.army.mil/Locations/Willamette-Valley/Injunction/).

## Graphics on this webpage

This webpage hosts:

* A timeline of project-by-project implementation measures, arranged by sub-basin. The timeline shows when different measures were implemented at which times, and shows instances where the measures had to be bypassed due to, e.g., flood risk mitigation. 
* An interactive map of rotary screw trap (RST) locations, showing the locations of the traps at each project of interest. By hovering over the map, you can see years in which each trap was active during pre- and post-injunction periods. 

Click the menu items in the header above to view.